Modules/Blog/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Blog\Http\Controllers\BlogController;
use Modules\Blog\Http\Controllers\UserBlogController;

Route::prefix('blog')->name('blogs.')->group(function() {
    Route::get('/create-blogs', [BlogController::class, 'create'])->name('create');
    Route::post('/store-blogs', [BlogController::class, 'store'])->name('store');
    Route::get('/view-blogs', [BlogController::class, 'view'])->name('view');
    Route::get('/show-blogs/{id}', [BlogController::class, 'show'])->name('show');
    Route::get('/edit-blogs/{id}', [BlogController::class, 'edit'])->name('edit');
    Route::post('/update-blogs/{id}', [BlogController::class, 'update'])->name('update');
    Route::get('/delete-blogs/{id}', [BlogController::class, 'destroy'])->name('delete');

});

Route::prefix('userblog')->name('userblogs.')->group(function() {
    Route::get('/create-blogs', [UserBlogController::class, 'create'])->name('create');
    Route::post('/store-blogs', [UserBlogController::class, 'store'])->name('store');

    Route::get('/edit-blogs/{id}', [UserBlogController::class, 'edit'])->name('edit');
    Route::post('/update-blogs/{id}', [UserBlogController::class, 'update'])->name('update');

    Route::get('/show-blogs/{id}', [UserBlogController::class, 'show'])->name('show');
    Route::get('/view-blogs', [UserBlogController::class, 'view'])->name('view');




});

Modules/Blog/Entities/Blog.php
<?php

namespace Modules\Blog\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Category\Entities\Category;

class Blog extends Model
{
    use HasFactory;
    public function categories(){
        return $this->belongsTo(Category::class, 'category_id');
     }

    protected $fillable = [
        'name',
        'category_id',
        'description',
        'image',
    ];

    protected static function newFactory()
    {
        return \Modules\Blog\Database\factories\BlogFactory::new();
    }
}

Modules/Blog/Http/Controllers/BlogController.php
<?php

namespace Modules\Blog\Http\Controllers;

use App\Repository\ImageRepository;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Blog\Repository\BlogRepository;
use Modules\Category\Repository\CategoryRepository;

class BlogController extends Controller
{

    private $blogRepository;
    private $categoryRepository;
    private $imageRepository;

    public function __construct(BlogRepository $blogRepository, CategoryRepository $categoryRepository, ImageRepository $imageRepository)
    {
        $this->blogRepository = $blogRepository;
        $this->categoryRepository = $categoryRepository;
        $this->imageRepository = $imageRepository;
    }

    public function show($id)
    {
        $blog =  $this->blogRepository->find($id);
        return view('blog::blogs.show-blogs', compact('blog'));
    }


    public function create()
    {
        $categories = $this->categoryRepository->all();
        return view('blog::blogs.create-blogs', compact('categories'));
    }


    public function store(Request $request)
    {
        // dd($request);

        try {
            $data = [
                'name' => $request->name,
                'category_id' => $request->category_id,
                'description' => $request->description,
                'image' => $this->imageRepository->saveImage($request, 'image', 'blogs')

            ];

             $this->blogRepository->create($data);


            return redirect()->route('blogs.view')->with('success', 'Added Successfully');
        } catch (\Exception $e) {

            return redirect()->route('blogs.view')->with('success', 'Unable to add');
        }
    }



    public function view(Request $request)
    {
        // dd($request);
        try{
        if (isset($request->search)) {
            $searches = $request->search;
            $blogs = $this->blogRepository->searchblogs($searches);
            return view('blog::blogs.view-blog', compact('blogs', 'searches'));
        } else {
            $blogs = $this->blogRepository->withcategory();
            return view('blog::blogs.view-blog', compact('blogs'));
        // dd($blogs);

        }
    }
        catch(\Exception $e){
            return $e->getMessage();

        }

    }



    public function edit($id)
    {
        $blog = $this->blogRepository->getcategories($id);
        $categories = $this->categoryRepository->all();
        return view('blog::blogs.edit-blogs', compact('blog', 'categories'));
    }



    public function update(Request $request, $id)
    {

        try {
            $blog = $this->blogRepository->find($id);
            $data = [
                'name' => $request->name,
                'category_id' => $request->category_id,
                'description' => $request->description,

            ];


            if ($request->hasFile('image')) {
                if ($blog->image) {
                    $this->imageRepository->removeImage($blog, 'image', 'blogs');
                }
                $data['image'] = $this->imageRepository->saveImage($request, 'image', 'blogs');
            }
            $this->blogRepository->update($data, $request->id);

            return redirect()->route('blogs.view')->with('success', 'Blog updated successfully');
        } catch (\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
    }


    public function destroy($id)
    {
        try {
            $blog = $this->blogRepository->find($id);
            $this->blogRepository->delete($blog->id);
            return redirect()->route('blogs.view')->with('success', "Deleted successfully.");
        } catch (\Exception $e) {
            return redirect()->route('blogs.view')->with('error', "Unable to delete.");
        }
    }
}

Modules/Blog/Resources/views/blogs/create-blogs.blade.php
@extends('dashboard::layouts.master')
@section('content')
    <div class="content-wrapper">
        <div class="container mt-4">

            <div class="card">
                <div class="card-header text-center font-weight-bold">
                    Create Blog
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('blogs.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group col-md-3">
                            <label for="name"> Blog Name</label>
                            <input type="text" id="name" name="name" class="form-control" required="">
                        </div>

                        <div class="dropdown col-md-3">
                            <label for="category_id">Category</label>
                            <select name="category_id" id="category_id">
                                <option>Select Category</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group col-md-4">
                            <label for="description">Description</label>
                            <textarea type="text" id="description" name="description" class="form-control" required=""></textarea>
                        </div>



                        <label class="col-lg-2 col-form-label text-right">Blog Image:</label>
                        <div class="col-lg-4">
                            <input type="file" name="image" required class="form-control mb-2"
                                placeholder="Choose Image" value="{{ old('image') }}" />
                            @error('image')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm">Add Blog</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

Modules/Blog/Resources/views/blogs/edit-blogs.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>

    <div class="content-wrapper">
        <div class="container mt-4">

            <div class="card">
                <div class="card-header text-center font-weight-bold">
                    Edit Blog
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('userblogs.update', ['id' => $blog->id]) }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group col-md-6">
                            <label for="name"> Blog Name</label>
                            <input type="text" id="name" name="name" class="form-control" required=""
                                value="{{ $blog->name }}">
                            <div><br>

                                <div class="dropdown col-md-3">
                                    <label for="category_id">Category</label>
                                    <select name="category_id" id="category_id">
                                        <option value="{{ optional($blog->categories)->id }}">
                                            {{ optional($blog->categories)->name }}</option>
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div><br>




                                <div class="form-group col-md-8">
                                    <label for="description">Description</label>
                                    <input type="text" id="description" name="description" class="form-control" required
                                        value="{{ $blog->description }}">
                                </div><br>


                                <div class="form-group col-md-6">
                                    <label for="image">Blog Image</label>
                                    <input type="file" id="image" name="image" class="form-control"
                                        value="{{ $blog->image }}">
                                    <img src="{{ url('uploads/images/blogs/' . $blog->image) }}"
                                        style="border-radius: 50%;" width="100px" height="100px" alt="No image Found">
                                </div><br>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    </body>


    </html>

Modules/Blog/Resources/views/blogs/show-blogs.blade.php
@extends('dashboard::layouts.master')
@section('content')
    <div class="content-wrapper">
        {{-- <div>
        @if (session()->has('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
    </div> --}}

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Image</th>
                    <th scope="col">Action</th>

                </tr>
            </thead>


            <tbody>

                <tr>
                    <td> {{ $blog->id }}</td>
                    <td> {{ $blog->name }}</td>
                    <td> {{ optional($blog->categories)->name }}</td>
                    <td>{{ $blog->description }} </td>
                    <td>
                        <img src="{{ url('uploads/images/blogs/' . $blog->image) }}" style="border-radius: 50%;"
                            width="100px" height="100px" alt="No image Found">
                    </td>
                    <td>
                        <a href="{{ route('blogs.edit', ['id' => $blog->id]) }}"
                            class="btn btn-primary btn-sm">Edit</a>
                        <a href="{{ url('blog/delete-blogs/' . $blog->id) }}"
                            class="btn btn-danger btn-sm">Delete</a>

                    </td>

                </tr>

            </tbody>
        </table>
        <a href="{{ url('/blog/create-blogs') }}" class="btn btn-xs btn-info pull-right">Add Blog</a>



    </div>

Modules/Blog/Resources/views/blogs/view-blog.blade.php
@extends('dashboard::layouts.master')
@section('content')
    <div class="content-wrapper">
        <div>
            @if (session()->has('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
        </div>

        <div class="topnav">
            <a href="{{ url('/blog/create-blogs') }}" class="btn btn-primary btn-info pull-right">Add Blog</a>
            <div class="container"><br>

                <form action="{{ route('blogs.view') }}" method="GET">
                    <div class="input-group" class="form-outline" class="col-9">
                        <input type="search" id="search" name="search" class="form-control"
                            placeholder="Search by name">
                        <button class="btn btn-primary">Search</button>

                </form>
            </div>
        </div>
    </div>




    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>
                <th scope="col">Action</th>

            </tr>
        </thead>


        @foreach ($blogs as $blog)
            <tbody>

                <tr>
                    <td> {{ $loop->iteration }}</td>
                    <td> {{ $blog->name }}</td>
                    <td> {{ optional($blog->categories)->name }}</td>
                    <td>{{ $blog->description }} </td>
                    <td>
                        <img src="{{ url('uploads/images/blogs/' . $blog->image) }}" style="border-radius: 50%;"
                            width="100px" height="100px" alt="No image Found">
                    </td>
                    <td>
                        <a href="{{ url('blog/show-blogs/' . $blog->id) }}"
                            class="btn btn-primary btn-sm">Show</a>
                        <a href="{{ route('blogs.edit', ['id' => $blog->id]) }}"
                            class="btn btn-primary btn-sm">Edit</a>
                        <a href="{{ url('blog/delete-blogs/' . $blog->id) }}"
                            class="btn btn-danger btn-sm">Delete</a>

                    </td>

                </tr>

            </tbody>
        @endforeach
    </table>

    {{-- continue pagination --}}
    <div class='dataTables_paginate paging_simple_numbers float-right card-body'>
        {{ $blogs->appends(Request::except('page'))->links('pagination::bootstrap-4') }}
    </div>
    </div>